### PR TITLE
ROC-4928 defence task list - display INCOMPLETE status

### PR DESCRIPTION
**Pull request by ellie-harrison**
Add a "INCOMPLETE" tag to a task when it's status is incomplete

### CODE REVIEW

**Comment by andrewwa-kainos** [comment]
Will the frontend break when this is merged before the frontend changes?

**Comment by andrewwa-kainos** [comment]
The new parameter is always true in the sibling PR (https://github.com/hmcts/cmc-citizen-frontend/pull/1384) - is there any need for the parameter?

**Comment by ellie-harrison** [comment]
> The new parameter is always true in the sibling PR ([hmcts/cmc-citizen-frontend#1384](https://github.com/hmcts/cmc-citizen-frontend/pull/1384)) - is there any need for the parameter?

It's only true on the response page task list. Every other instance in every other task list doesn't pass it though, defaulting the check on it to resolve to false.

**Comment by ellie-harrison** [comment]
> Will the frontend break when this is merged before the frontend changes?

It will, I will have to revise this to keep compatible CSS class names

**Review by andrewwa-kainos — APPROVED** [review]

**Review by KiranVarma02 — APPROVED** [review]

**Review by singh-surjeet — APPROVED** [review]

**Pull request merged**
